spring:
  application:
    name: user-application
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://185.103.70.190:15432/users_service_db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
server:
  port: 8081

spring.config.import: classpath:/security-config.yml