version: "3.8"

services:

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway-build
    environment:
      - GATEWAY_EMPLOYEE_URI=http://employee:8082/
      - GATEWAY_CORE_URI=http://core:8083/
      - GETEWAY_LOAN_URI=http://loan:8084/
    ports:
      - "8080:8080"
    networks:
      - my-network

  user:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-build
    expose:
      - "8081"
    networks:
      - my-network

  employee:
    build:
      context: .
      dockerfile: Dockerfile
      target: employee-build
    environment:
      - USER_SERVICE_URL=http://user:8081/
      - BILL_SERVICE_URL=http://core:8083/
      - LOAN_SERVICE_URL=http://loan:8084/
    expose:
      - "8082"
    networks:
      - my-network

  core:
    build:
      context: .
      dockerfile: Dockerfile
      target: core-build
    environment:
      - USER_SERVICE_URL=http://user:8081/
    expose:
      - "8083"
    networks:
      - my-network

  loan:
    build:
      context: .
      dockerfile: Dockerfile
      target: loan-build
    environment:
      - USER_SERVICE_URL=http://user:8081/
      - BILL_SERVICE_URL=http://core:8083/
    expose:
      - "8084"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge