spring:
  application:
    name: employee-application
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://185.103.70.190:15432/USERS_SERVICE_DB
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

spring.config.import: classpath:/security-config.yml