name: Build and Run Docker Compose

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'

jobs:
  build-run:
    runs-on: self-hosted
    steps:
      - name: Проверка доступа к докер
        run: docker-compose ps

      - name: Оповещение об начале деплоя
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=Сервер начал деплой!!!"

      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Остановка контейнеров перед билдом (если нужно)
        run: docker-compose down || true

      - name: Пересборка сервисов
        run: docker-compose up --build -d

      - name: Проверка запущенных контейнеров
        run: docker ps -a

      - name: Оповещение об успехе деплоя
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=🚀 Новая версия уже на сервере скорее проверяй!!!"

      - name: Ошибка
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=❌ *Ошибка в CI/CD!*%0A📂 Репозиторий: ${{ github.repository }}%0A🔧 Джоб: ${{ github.job }}%0A🔗 Лог: [Просмотр](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
          -d "parse_mode=Markdown"